-- 将该建表 SQL 语句，添加到 yudao-module-distribution-biz 模块的 test/resources/sql/create_tables.sql 文件里
CREATE TABLE IF NOT EXISTS "distribution_comprehensive_order_info" (
    "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "order_date" varchar NOT NULL,
    "comprehensive_order_code" varchar NOT NULL,
    "comprehensive_order_file_name" varchar NOT NULL,
    "comprehensive_order_file_url" varchar NOT NULL,
    "total_order_number" int NOT NULL,
    "total_order_sales_amount" varchar NOT NULL,
    "total_order_cost_amount" varchar NOT NULL,
    "total_order_plan_profit_amount" varchar NOT NULL,
    "settlement_flag" varchar NOT NULL,
    "settlement_time" varchar,
    "total_order_transactions_number" int,
    "total_order_return_number" int,
    "total_order_actual_profit_amount" varchar,
    "deleted" bit NOT NULL DEFAULT FALSE,
    "deleted_time" varchar,
    "note" varchar,
    "creator" varchar DEFAULT '',
    "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updater" varchar DEFAULT '',
    "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY ("id")
) COMMENT '配货综合订单信息表';

-- 将该删表 SQL 语句，添加到 yudao-module-distribution-biz 模块的 test/resources/sql/clean.sql 文件里
DELETE FROM "distribution_comprehensive_order_info";
